/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsFiltersRouteImport } from './routes/settings.filters'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsDefaultCriteriaRouteImport } from './routes/settings.default-criteria'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as DevLogsRouteImport } from './routes/dev.logs'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiRecordsRouteImport } from './routes/api/records'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDiagnosticsRouteImport } from './routes/api/diagnostics'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiScraperLogsStreamRouteImport } from './routes/api/scraper-logs.stream'
import { Route as ApiReportsPdfRouteImport } from './routes/api/reports/pdf'
import { Route as ApiDevAuthRouteImport } from './routes/api/dev/auth'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ClientsClientIdCasesCaseIdRouteImport } from './routes/clients.$clientId.cases.$caseId'
import { Route as ApiPublicHooksCleanupLogsRouteImport } from './routes/api/public/hooks/cleanup-logs'
import { Route as ApiPublicHooksCasesRefreshRouteImport } from './routes/api/public/hooks/cases-refresh'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFiltersRoute = SettingsFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDefaultCriteriaRoute = SettingsDefaultCriteriaRouteImport.update({
  id: '/default-criteria',
  path: '/default-criteria',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const DevLogsRoute = DevLogsRouteImport.update({
  id: '/dev/logs',
  path: '/dev/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRoute = ApiRecordsRouteImport.update({
  id: '/api/records',
  path: '/api/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticsRoute = ApiDiagnosticsRouteImport.update({
  id: '/api/diagnostics',
  path: '/api/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScraperLogsStreamRoute = ApiScraperLogsStreamRouteImport.update({
  id: '/api/scraper-logs/stream',
  path: '/api/scraper-logs/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsPdfRoute = ApiReportsPdfRouteImport.update({
  id: '/api/reports/pdf',
  path: '/api/reports/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevAuthRoute = ApiDevAuthRouteImport.update({
  id: '/api/dev/auth',
  path: '/api/dev/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsClientIdCasesCaseIdRoute =
  ClientsClientIdCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)
const ApiPublicHooksCleanupLogsRoute =
  ApiPublicHooksCleanupLogsRouteImport.update({
    id: '/api/public/hooks/cleanup-logs',
    path: '/api/public/hooks/cleanup-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCasesRefreshRoute =
  ApiPublicHooksCasesRefreshRouteImport.update({
    id: '/api/public/hooks/cases-refresh',
    path: '/api/public/hooks/cases-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/dev/logs': typeof DevLogsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/default-criteria': typeof SettingsDefaultCriteriaRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/filters': typeof SettingsFiltersRoute
  '/settings/': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cases-refresh': typeof ApiPublicHooksCasesRefreshRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
  '/clients/$clientId/cases/$caseId': typeof ClientsClientIdCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/records': typeof RecordsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/dev/logs': typeof DevLogsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/default-criteria': typeof SettingsDefaultCriteriaRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/filters': typeof SettingsFiltersRoute
  '/settings': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cases-refresh': typeof ApiPublicHooksCasesRefreshRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
  '/clients/$clientId/cases/$caseId': typeof ClientsClientIdCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/database': typeof DatabaseRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/watchlist': typeof WatchlistRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/config': typeof ApiConfigRoute
  '/api/diagnostics': typeof ApiDiagnosticsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/records': typeof ApiRecordsRoute
  '/api/version': typeof ApiVersionRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/dev/logs': typeof DevLogsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/default-criteria': typeof SettingsDefaultCriteriaRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/filters': typeof SettingsFiltersRoute
  '/settings/': typeof SettingsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/dev/auth': typeof ApiDevAuthRoute
  '/api/reports/pdf': typeof ApiReportsPdfRoute
  '/api/scraper-logs/stream': typeof ApiScraperLogsStreamRoute
  '/api/public/hooks/cases-refresh': typeof ApiPublicHooksCasesRefreshRoute
  '/api/public/hooks/cleanup-logs': typeof ApiPublicHooksCleanupLogsRoute
  '/clients/$clientId/cases/$caseId': typeof ClientsClientIdCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/clients'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/mcp'
    | '/records'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/diagnostics'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/clients/$clientId'
    | '/dev/logs'
    | '/settings/ai'
    | '/settings/default-criteria'
    | '/settings/diagnostics'
    | '/settings/filters'
    | '/settings/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cases-refresh'
    | '/api/public/hooks/cleanup-logs'
    | '/clients/$clientId/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/clients'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/mcp'
    | '/records'
    | '/sitemap.xml'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/diagnostics'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/clients/$clientId'
    | '/dev/logs'
    | '/settings/ai'
    | '/settings/default-criteria'
    | '/settings/diagnostics'
    | '/settings/filters'
    | '/settings'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cases-refresh'
    | '/api/public/hooks/cleanup-logs'
    | '/clients/$clientId/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/clients'
    | '/dashboard'
    | '/database'
    | '/jobs'
    | '/mcp'
    | '/records'
    | '/settings'
    | '/sitemap.xml'
    | '/watchlist'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/config'
    | '/api/diagnostics'
    | '/api/health'
    | '/api/records'
    | '/api/version'
    | '/clients/$clientId'
    | '/dev/logs'
    | '/settings/ai'
    | '/settings/default-criteria'
    | '/settings/diagnostics'
    | '/settings/filters'
    | '/settings/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/dev/auth'
    | '/api/reports/pdf'
    | '/api/scraper-logs/stream'
    | '/api/public/hooks/cases-refresh'
    | '/api/public/hooks/cleanup-logs'
    | '/clients/$clientId/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DatabaseRoute: typeof DatabaseRoute
  JobsRoute: typeof JobsRoute
  McpRoute: typeof McpRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WatchlistRoute: typeof WatchlistRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiDiagnosticsRoute: typeof ApiDiagnosticsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecordsRoute: typeof ApiRecordsRoute
  ApiVersionRoute: typeof ApiVersionRoute
  DevLogsRoute: typeof DevLogsRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiDevAuthRoute: typeof ApiDevAuthRoute
  ApiReportsPdfRoute: typeof ApiReportsPdfRoute
  ApiScraperLogsStreamRoute: typeof ApiScraperLogsStreamRoute
  ApiPublicHooksCasesRefreshRoute: typeof ApiPublicHooksCasesRefreshRoute
  ApiPublicHooksCleanupLogsRoute: typeof ApiPublicHooksCleanupLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/filters': {
      id: '/settings/filters'
      path: '/filters'
      fullPath: '/settings/filters'
      preLoaderRoute: typeof SettingsFiltersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/default-criteria': {
      id: '/settings/default-criteria'
      path: '/default-criteria'
      fullPath: '/settings/default-criteria'
      preLoaderRoute: typeof SettingsDefaultCriteriaRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/dev/logs': {
      id: '/dev/logs'
      path: '/dev/logs'
      fullPath: '/dev/logs'
      preLoaderRoute: typeof DevLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records': {
      id: '/api/records'
      path: '/api/records'
      fullPath: '/api/records'
      preLoaderRoute: typeof ApiRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostics': {
      id: '/api/diagnostics'
      path: '/api/diagnostics'
      fullPath: '/api/diagnostics'
      preLoaderRoute: typeof ApiDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scraper-logs/stream': {
      id: '/api/scraper-logs/stream'
      path: '/api/scraper-logs/stream'
      fullPath: '/api/scraper-logs/stream'
      preLoaderRoute: typeof ApiScraperLogsStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/pdf': {
      id: '/api/reports/pdf'
      path: '/api/reports/pdf'
      fullPath: '/api/reports/pdf'
      preLoaderRoute: typeof ApiReportsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/auth': {
      id: '/api/dev/auth'
      path: '/api/dev/auth'
      fullPath: '/api/dev/auth'
      preLoaderRoute: typeof ApiDevAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/cases/$caseId': {
      id: '/clients/$clientId/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/clients/$clientId/cases/$caseId'
      preLoaderRoute: typeof ClientsClientIdCasesCaseIdRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/api/public/hooks/cleanup-logs': {
      id: '/api/public/hooks/cleanup-logs'
      path: '/api/public/hooks/cleanup-logs'
      fullPath: '/api/public/hooks/cleanup-logs'
      preLoaderRoute: typeof ApiPublicHooksCleanupLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cases-refresh': {
      id: '/api/public/hooks/cases-refresh'
      path: '/api/public/hooks/cases-refresh'
      fullPath: '/api/public/hooks/cases-refresh'
      preLoaderRoute: typeof ApiPublicHooksCasesRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdCasesCaseIdRoute: typeof ClientsClientIdCasesCaseIdRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdCasesCaseIdRoute: ClientsClientIdCasesCaseIdRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface SettingsRouteChildren {
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsDefaultCriteriaRoute: typeof SettingsDefaultCriteriaRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsFiltersRoute: typeof SettingsFiltersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAiRoute: SettingsAiRoute,
  SettingsDefaultCriteriaRoute: SettingsDefaultCriteriaRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsFiltersRoute: SettingsFiltersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DatabaseRoute: DatabaseRoute,
  JobsRoute: JobsRoute,
  McpRoute: McpRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WatchlistRoute: WatchlistRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiDiagnosticsRoute: ApiDiagnosticsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecordsRoute: ApiRecordsRoute,
  ApiVersionRoute: ApiVersionRoute,
  DevLogsRoute: DevLogsRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiDevAuthRoute: ApiDevAuthRoute,
  ApiReportsPdfRoute: ApiReportsPdfRoute,
  ApiScraperLogsStreamRoute: ApiScraperLogsStreamRoute,
  ApiPublicHooksCasesRefreshRoute: ApiPublicHooksCasesRefreshRoute,
  ApiPublicHooksCleanupLogsRoute: ApiPublicHooksCleanupLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
